-- CREATE TABLE "order"
-- (
--     orderId       integer NOT NULL PRIMARY KEY,
--     customer      text,
--     location      text,
--     address       text,
--     code          text,
--     dataReady     date,
--     dataPayment   date,
--     price         integer,
--     profit        integer,
--     priority      integer,
--     orderType     text,
--     numberAkt     text,
--     inTheProgress boolean,
--     toTheAkt      boolean
-- );
